name: verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ## Verify module, terraform validate runs only on examples
  terraform_module:
    name: terraform module
    strategy:
      matrix:
        terraform: [1.0.0]
    runs-on: [self-hosted, research]
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v2

      - uses: philips-labs/terraform-private-modules-action@v1.1
        with:
          org: philips-internal
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: check formatting
        run: terraform fmt -recursive -check=true -write=false

      - name: init terraform
        run: terraform init -get -backend=false -input=false

  ## Verify examples, terraform fmt runs only on module version.
  terraform_examples:
    name: terraform examples
    strategy:
      matrix:
        terraform: [0.14.4, latest]
        example: ["simple"]
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    runs-on: [self-hosted, research]
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v2

      - uses: philips-labs/terraform-private-modules-action@v1.1
        with:
          org: philips-internal
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: check formatting
        if: ${{ matrix.terraform == '0.14.4' }}
        run: terraform fmt -recursive -check=true -write=false

      - name: init terraform example
        run: terraform init -get -backend=false -input=false

      - name: validate terraform
        run: terraform validate

  checkov:
    name: Checkov scan
    runs-on: [self-hosted, research]
    container: bridgecrew/checkov
    steps:
      - uses: actions/checkout@v2

      - uses: philips-labs/terraform-private-modules-action@v1.1
        with:
          org: philips-internal
          token: ${{ secrets.GH_PAT_TOKEN }}

      # The external-checks-git will clone the policies repository in the current working directory. Due to a bug, this will break checkov when executed from the same.
      # To work around this, checkov is executed one level up. See: https://github.com/bridgecrewio/checkov/issues/1778
      - run: checkov --directory $GITHUB_WORKSPACE --external-checks-git https://github.com/philips-internal/checkov-custom-policies-terraform-modules.git
        working-directory: ${{ github.workspace }}/..
